### ISSUE TITLE
QUnit: I am unable to complete a successful test using `grunt test`

### ISSUE THREAD

**Issue by kjbenk** [WP-API/client-js#108]
How to Replicate:

1. From the command line perform the `npm install` and `nam run build` commands

I got an output like this within my `npm-debug.log` file

``` log
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.7.5
3 info using node@v0.10.37
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
6 info lifecycle wp-api-client-js@0.1.0~prebuild: wp-api-client-js@0.1.0
7 silly lifecycle wp-api-client-js@0.1.0~prebuild: no script for prebuild, continuing
8 info lifecycle wp-api-client-js@0.1.0~build: wp-api-client-js@0.1.0
9 verbose lifecycle wp-api-client-js@0.1.0~build: unsafe-perm in lifecycle true
10 verbose lifecycle wp-api-client-js@0.1.0~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/srv/www/wordpress-default/wp-content/plugins/client-js/node_modules/.bin:/usr/bin:/home/vagrant/bin:/usr/local/rvm/gems/ruby-2.2.1/bin:/usr/local/rvm/gems/ruby-2.2.1@global/bin:/usr/local/rvm/rubies/ruby-2.2.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/rvm/bin:/srv/www/phpcs/scripts/
11 verbose lifecycle wp-api-client-js@0.1.0~build: CWD: /srv/www/wordpress-default/wp-content/plugins/client-js
12 silly lifecycle wp-api-client-js@0.1.0~build: Args: [ '-c', 'grunt' ]
13 silly lifecycle wp-api-client-js@0.1.0~build: Returned: code: 6  signal: null
14 info lifecycle wp-api-client-js@0.1.0~build: Failed to exec build script
15 verbose stack Error: wp-api-client-js@0.1.0 build: `grunt`
15 verbose stack Exit status 6
15 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
15 verbose stack     at EventEmitter.emit (events.js:98:17)
15 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
15 verbose stack     at ChildProcess.emit (events.js:98:17)
15 verbose stack     at maybeClose (child_process.js:766:16)
15 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
16 verbose pkgid wp-api-client-js@0.1.0
17 verbose cwd /srv/www/wordpress-default/wp-content/plugins/client-js
18 error Linux 3.13.0-77-generic
19 error argv "node" "/usr/bin/npm" "run" "build"
20 error node v0.10.37
21 error npm  v3.7.5
22 error code ELIFECYCLE
23 error wp-api-client-js@0.1.0 build: `grunt`
23 error Exit status 6
24 error Failed at the wp-api-client-js@0.1.0 build script 'grunt'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the wp-api-client-js package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     grunt
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs wp-api-client-js
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls wp-api-client-js
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

When I tested within he browser the tests seemed to work just fine, so the error must be within the command line.

![Browser Testing](https://cldup.com/FRZAVFLZSq.png)

**Comment by adamsilverstein** [comment]
Can you try running the tests with:

`grunt qunit`

check that gruntfile points to your local install correctly.

**Comment by kjbenk** [comment]
Ok I was able to get the tests to run via the command line by editing this line within  `/Gruntfile.js`.  Just like you mentioned I needed to change the url from:

`http://localhost:80/wp-content/plugins/client-js/tests/tests.html`
to
`http://local.wordpress.dev/wp-content/plugins/client-js/tests/tests.html`

since I am running it on a VVV env.

The tests are still failing however so I will keep this issue open.

**Comment by adamsilverstein** [comment]
Noting that all tests pass for me.

**Comment by adamsilverstein** [comment]
@kjbenk can you try running the tests with the command `grunt qunit`? These tests work fine for my local setup:

![tests](http://cl.ly/3Z103O1o1P1i/1._adamsilversteinAdams-MacBook-Pro-2_repositoriesclient-js_zsh_2016-05-26_09-54-00.jpg)

**Comment by adamsilverstein** [comment]
Closing this out as the code has merged to WordPress core. I will work on getting these tests running in wp core.
